[API]
account = "python-ireland"
event = "pycon-ireland-2025"

[Database]
conn_string = "sqlite:///pycon-2025.db"
echo = false

[Printout]
title = "Pycon Ireland 2025"
include_title = false
background = "trinity_knot_green_transparent_bg.png"
paper_size = "A5"
show_guidelines = false
debug = true

[fonts]
#reference_font = "UbuntuMono-R.ttf"
reference_font = "Courier New.ttf"
conference_font = "BreeBold.ttf"
name_font = "BreeSerif-Regular.ttf"
